AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pseudo:
            type: string
            length: 255
            unique: true
        classement:
            type: string
            length: 255
        mail:
            type: string
            length: 255
            nullable: true
            unique: true
        idFacebook:
            type: integer
            length: 255
            nullable: true
            unique: true
    lifecycleCallbacks: {  }
